### PR TITLE
Add Nothing Metadata

### PR DESCRIPTION
**Pull request by moodscripted**

### CODE REVIEW

**Comment by jyap808** [comment]
Please resolve the merge conflict.

Also: Resize logos to 200px and run through https://tinypng.com/

**Comment by moodscripted** [comment]
Forgot to check that. Will do

**Comment by jyap808** [comment]
Make sure you pull the latest changes to the repo as well. This will prevent a merge conflict.

**Comment by moodscripted** [comment]
Sorry about that. Submitted a new one and closed this.

**Pull request closed without merging**
